# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Hints that apply only to the HLint source code

#####################################################################
## RESTRICTIONS

- extensions:
  - default: true
