name:                miuki
version:             0.1.0.0
github:              "theindigamer/miu"
license:             BSD3
author:              "Varun Gandhi"
maintainer:          "theindigamer15@gmail.com"
copyright:           "2018 Varun Gandhi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/miuki#readme>

dependencies:
- base >= 4.10 && < 5

library:
  source-dirs: src

default-extensions:
  LambdaCase
  TupleSections
  BangPatterns
  NamedFieldPuns
  OverloadedStrings
  FlexibleContexts
  FlexibleInstances
  MultiParamTypeClasses
  DeriveFunctor
  DeriveFoldable
  DeriveTraversable
  DeriveGeneric
  DeriveDataTypeable
  StandaloneDeriving

ghc-options:
  -Wall
  -Wincomplete-uni-patterns
  -Wnoncanonical-monad-instances
  -Wnoncanonical-monoid-instances
  -Wcompat
  -funbox-strict-fields

executables:
  miuki:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miuki

tests:
  miuki-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miuki
