name:                miuki-hs
version:             0.1.0.0
github:              "theindigamer/miu"
license:             MPL-2.0
author:              "Varun Gandhi <theindigamer15@gmail.com>"
maintainer:          "Varun Gandhi <theindigamer15@gmail.com>"
copyright:           "2019 Varun Gandhi"

extra-source-files:
- Readme.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A scratchpad for features in Miuki.

dependencies:
- base >= 4.11 && < 5
- megaparsec
- text
- containers
- unordered-containers
- hashable
- vector

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wmonomorphism-restriction
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -Wnoncanonical-monoid-instances
- -Wredundant-constraints
- -Widentities
- -Wno-type-defaults
- -Wpartial-fields
- -funbox-strict-fields

default-extensions:
- OverloadedStrings # remove this if it interacts badly with Shake.
- BangPatterns
- LambdaCase
- NamedFieldPuns
- TupleSections
- MultiWayIf
- InstanceSigs
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- StandaloneDeriving
- FlexibleInstances
- FlexibleContexts
- MultiParamTypeClasses
- GADTs

executables:
  miuki_hs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miuki-hs

tests:
  miuki-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miuki-hs
